[project]
name = "pai-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-ai>=1.41.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.11",
]
